### ISSUE TITLE
[Feature Request] Add drop down menu for streams list.

### ISSUE THREAD

**Issue by thejustsoul** [Hunter5000/Twitch-Alarm#1]
Add drop down menu with a list of streams if you can. To left click caused this menu and not 1 stream from 5 available (of which 3 online) for example.

**Comment by Hunter5000** [comment]
I think this feature has been added as of version 1.0.0.    

Feel free to reply if you meant something different than what I implemented.

**Comment by thejustsoul** [comment]
I have nothing to compare appearance, but with this extension - ([TwitchLive](https://chrome.google.com/webstore/detail/twitchlive/imcjibojeokeogfofjgaajlobobagbeg)) for Chromium. I would like a similar design drop-down list.

If possible, also add the number of viewers and avatar channel. And the ability to hide inactive channels (without entering in settings), for example as is done in TwitchLive, down arrow appears to the entire list.

If you have the ability to install Chromium and this extension and see how it is done. If you improve your addon, it will be best that there is for Firefox.

offtop: Do you speak Russian?

**Comment by Hunter5000** [comment]
I will check out TwitchLive. Now that I have a grasp of modifying HTML with JavaScript I can probably start making the interface more accessible.

And no I do not speak Russian. After noticing that a fair portion of my user demographic uses Russian Firefox, I asked for people to help me localize. GitHub user sasa8585 was generous enough to translate the preferences of this add-on. Hopefully I can get a German localization, there's almost as many German users as there are English.

**Comment by Hunter5000** [comment]
Check out the newest version on GitHub, 1.2.0. I do not want to upload it to AMO yet because i want 1.1.1 to go through first. I have made the user interface in a fashion that I think is quite comparable to TwitchLive. I'd like to hear your input.

**Comment by thejustsoul** [comment]
Well. But it seems too rough, if you can, do this menu is smaller/more compact. 
What is the "Latest online streamer" and "Other online streamers", why not leave only Online, Offline.

Not to create a new ticket, I'll write here if you don't mind.
- Add feature to add a channel by entering the channel (browser) which is not in the list (and not through settings).
- Add buttons in GUI to add/remove the channel and hide/show Offline.
- Add option to hide labels Online/Offline if select hide Offline.

Noticed a bug, if there is an active stream, then after the computer from sparago mode, they remain Online, but actually already Offline.
Until next time, I will write later if anything else comes to mind.

**Comment by Hunter5000** [comment]
I've created a new version that lets you hide/show streamers as well as sorting by most recent streams or streams with the most viewers. I haven't added the ability to change preference settings via the interface yet. I will likely add that feature when I completely overhaul the preferences UI into the panel format.

**Comment by thejustsoul** [comment]
Another bug (`v1.3.1`) - counter viewers sometimes shows 0, but actually a larger audience. 

About bug with sleep mode Windows wrote above, after leaving it, the information is not updated about the stream and shows what it was before.

UPD:
So in the logs at the time: 
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer1
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer2
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer3
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer4
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer5
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer6
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer7
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer4
22:09:33                xhr     https://api.twitch.tv/kraken/streams/streamer6

`streamer4` and `streamer6` real online, in logs two times at one reqest (reason for "0 viewers"?).

**Comment by thejustsoul** [comment]
So in the logs at the time: 
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer1
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer2
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer3
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer4
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer5
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer6
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer7
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer4
22:09:33				xhr 	https://api.twitch.tv/kraken/streams/streamer6

`streamer4` and `streamer6` real online, in logs two times at one reqest (reason for "0 viewers"?).

**Comment by Hunter5000** [comment]
It's been awhile. The bug you mentioned above has been fixed and the settings have all been moved to a panel format. I'd like to hear your thoughts on it now, if you're still there.

**Comment by thejustsoul** [comment]
On account bug "does not update the status after hibernation, can't tell until you have tested it. But even in normal mode, the channel is turned off, but the status was not updated. In the logs still many simultaneous requests (!), maybe this causes problems with updating the status of the channel. Figured out how to make instead of many requests and parse the response? Here's what it looks like when one channel goes offline: 

![Image](http://storage1.static.itmages.ru/i/15/0529/h_1432924838_6256347_75f5f7cd1d.png)

P. S. Why not move the buttons and labels in the bottom right or left corner in one line, and reduce the size? And then take up too much useful space.

UPD: Add if you can import from a text file from a text field and multiple channels at once. Another good idea would be to pick up the previous settings when update addon to new version.

**Comment by thejustsoul** [comment]
Here's another idea for a new feature:
If you do not want to miss an important stream, which will soon begin, mark him a star (for example), and when it is on the network, you receive a browser notification (something like this: http://habrahabr.ru/post/183630/, http://delch.github.io/notifications-api/ or another) by clicking on which will open the stream (in the browser, livestreamer, etc, as specified in settings).

**Comment by Hunter5000** [comment]
The interface has come a long way since this issue was opened! I think this issue is no longer relevant, even if the interface itself is not perfect.
