### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by coast-dev** [Hunter5000/Twitch-Alarm#11]
Add 100+ channels to follow and watch memory consumption. For me it is eating around 1MB/s until there is no memory left and firefox freezes.

**Comment by Hunter5000** [comment]
As a result of the changes made in 1.12.10 and afterwards, I think this issue may be fixed. Please update if you haven't already and report back if you see any issues.

**Comment by coast-dev** [comment]
I've been testing 1.12.14 for few hours and no memory problems anymore.
