### ISSUE TITLE
Signing out everyday

### ISSUE THREAD

**Issue by OneNot** [Hunter5000/Twitch-Alarm#14]
TwitchFox keeps signing me out, so that every day, I have to sign back in.
I can't remember how long this has been a problem, but at least back when the name was different it wasn't a problem.

This issue defeats the point of the addon, as the whole point is that I don't have to remember to worry about checking if streamers are online or not.

**Comment by Hunter5000** [comment]
I've removed the automatic logging out feature (it was supposed to log you out when your authentication token expires, but it wasn't working) in Twitch Fox version 3.0.0. Please report to me after you have upgraded to this version if the issue still persists.

**Comment by OneNot** [comment]
Yeah, it has been working for a while now. Somewhere around a few days to a week. I didn't actively seek out an update, but I suppose it must have updated at some point. (I have automatic updates on)
Thanks for the update! :+1:
