### ISSUE TITLE
Automatic settings from previous version wiped, now have to do everything via pop-up menu manually

### ISSUE THREAD

**Issue by DashKrimson** [Hunter5000/Twitch-Alarm#15]
I just had this issue with TF 3.0.1 on Firefox 43.0.3, now, every single time I open a stream, I have to open every stream in Livestreamer and chat in a separate window (my preferred settings) manually, when the previous version used to do it automatically. Can you please do something about this, since having to do that for every stream is a right pain in the ass? Thanks in advance, and for an otherwise brilliant add-on!

**Comment by Hunter5000** [comment]
I'm getting to this right away. Hopefully by the end of today I will have solved this issue.

**Comment by DashKrimson** [comment]
Thank you for the rapid reply, good to know you're on your toes.

Looking forward to the results of your hard work, as always.

**Comment by Hunter5000** [comment]
Version 3.1.0 has been fully reviewed on the AMO. Please report to me after you have upgraded to and tested the issue on this version.

**Comment by DashKrimson** [comment]
Excellent, after a bit of setting up, the app behaves just how it should again. One thing, though; the first tickbox on the third options page isn't labelled, but I'm assuming that's what is bringing up the pop-up menus that appear when you click on a stream to open it?

Either way, thanks again for the good work!
