### ISSUE TITLE
Some settings on linux and Firefox Nightlys not remembered (ver. 3.1.3) (fixed in 3.1.8)

### ISSUE THREAD

**Issue by Stebs** [Hunter5000/Twitch-Alarm#17]
After every restart of Firefox, the settings on the last settings tab (beginning with dark mode) are lost.
If I open that tab, there is no checkmark visible and at the base, it says "Livestreamer was not found".
Clicking on "Reset to default", it says "Livestreamer is ready". Also, checkmark on "Create a popup" is set.
I can change that setting to my preference (disable "Create on popup" and enable "Open stream with Livestreamer) and everything then works as intended, but upon restart of Firefox, settings of this tab are lost again.
Settings of other two tabs seem to be ok though.

This only happens with Firefox Nightlys (currently 46.0a1 (2016-01-10)), Firefox 43 is ok.
But since Nightlys will one day become releases...

Have currenty only linux to test (so dont know if this is linux only), but it happens on 2 different machines.
Previous versions of Twitch-Fox where ok (before the redesign).

Settings seem to be in /firefox_profile_name/jetpack/jid1-PmBVeuWLfYr73g@jetpack/simple-storage/store.json
Last part of that file:
"interDarkMode":false,"interFollowedMode":true,"interHideAvatar":false,"interHideOffline":false,"interHidePreview":false,"interLivestreamerPath":"","interLivestreamerQuality":"best","interMode":"channels","interOpenChat":false,"interOpenLive":true,"interOpenPage":false,"interOpenPopout":false,"interOpenPopup":false,"interSearchLim":20,"interSortMethod":"viewers"}
Those seem like I want to, and are not changed after a restart! so is the problem with reading those settings?
BTW, channels are stored in another folder, is that intended?:
 /firefox_profile_name/jetpack/jid0-2wAjbeFD5dTCgsj70eQ6UAqQl4@jetpack/simple-storage/store.json

**Comment by Stebs** [comment]
Forget about the second folder (the last remark), probably leftover from an old version. I deleted both folders, and now there is only one.

Further analysis shows that all settings on 3. tab are correctly remembered, but "Open stream with Livestreamer" is not shown (and no stream is opened with livestreamer upon clicking on the stream), probably because livestreamer is not found until you click on "Reset to default"...
When setting path manually to /usr/bin/livestreamer
Livestreamer is correctly found, but this is also lost upon restart...
BTW, /usr/bin/livestreamer is correct here on arch linux, for others it may be /bin/livestreamer etc.
Although at least arch has link from /bin to /usr/bin, so both would work.

**Comment by Stebs** [comment]
Upon Nightly start, there is one error in Browser Console:
"ReferenceError: addon is not defined"  link on twitchFox.js points to:
addon.port.on("forcePrompt", function(payload) {

Same happens with Firefox 43 though.
Even copied store.json from Firefox 43 to Nightly, but still, in 43 it works, in Nightly not...

**Comment by Hunter5000** [comment]
Do any of these issues occur on 43? It doesn't sound like it, but just making sure. I looked at the areas of code that may possibly be the source of the issue and found no problems. "addon is not defined" is a weird error indeed. I'll have to look into how the Nightly build of Firefox may have changed how add-on specific code works.

**Comment by Stebs** [comment]
No, all issues only occur on Firefox Nightly (don't know about Beta or Aurora, didn't test with these). With 43 all is well. But as todays Nightlys will become Auroras, Betas and the Releases, those problems will some day reach the wide audience...

**Comment by Stebs** [comment]
Still occuring in 3.1.6

**Comment by Stebs** [comment]
Ah, just got another update to 3.1.8.
And the issue is fixed.
Well done!
