### ISSUE TITLE
Query optimization?

### ISSUE THREAD

**Issue by thejustsoul** [Hunter5000/Twitch-Alarm#2]
Maybe we should do optimization of queries to one query for each channel, but several channels in a single request. In another ([TwitchLive](https://chrome.google.com/webstore/detail/twitchlive/imcjibojeokeogfofjgaajlobobagbeg)) extension in Chromium, for example made so `(more channels=1 query)`:

`https://api.twitch.tv/kraken/streams?channel=channel1,channel2,channel3`

In your extension `(1 channel=1 query)`:

`https://api.twitch.tv/kraken/streams/channel1`
`https://api.twitch.tv/kraken/streams/channel2`
`https://api.twitch.tv/kraken/streams/channel3`

**Comment by Hunter5000** [comment]
This is a good idea. Can you provide an example of how it would work in the code? I'll investigate it more when I get home later today.

**Comment by thejustsoul** [comment]
Unfortunately, I don't have the programming skills of extensions, so can't help with code, I write on behalf of a regular user :) But probably you can see how it's done in TwitchLive.

**Comment by Hunter5000** [comment]
I've finally added this. I should've added it quite a long time ago, but I maintained the mindset of "don't fix what works."

Oh well, at least now it is fixed.
